### ISSUE TITLE
remove dot in the end of "freedom" value 

### ISSUE THREAD

**Issue by brunarostm** [mr3saru/landing#41]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/100144397/154981784-402d2f49-96de-4b62-940b-54076673c155.png">

**Comment by losito105** [comment]
Rather than remove the `.` at the end of the `Freedom` section, I would suggest instead adding a `.` to the end of the `Commitment`, `Confidence`, and `Customer centered` sections. This is just a suggestion but I'd be happy to make whatever change is preferred here.

**Comment by brunarostm** [comment]
Hi Tim, please just remove it at the end of "freedom" section. Cheers!

**Comment by losito105** [comment]
> Hi Tim, please just remove it at the end of "freedom" section. Cheers!

Will do, thank you!
