### ISSUE TITLE
Twitter, LinkedIn and Instagram icons linked to the respective pages

### ISSUE THREAD

**Issue by brunarostm** [mr3saru/landing#43]
- twitter: https://twitter.com/MrSaruit
- instagram: https://www.instagram.com/mrsaruit/
- linkedin: https://www.linkedin.com/company/mrsaru/

**Comment by losito105** [comment]
Hi! I've submitted a PR for this issue here: https://github.com/mr3saru/landing/pull/68.

**Comment by vczb** [comment]
@losito105  You are welcome!

**Comment by vczb** [comment]
> Hi! I've submitted a PR for this issue here: #68.

merged, congrats :1st_place_medal:
