### ISSUE TITLE
Put version number in footer

### ISSUE THREAD

**Issue by vameri** [mr3saru/landing#61]
![version_license](https://user-images.githubusercontent.com/3050155/157152715-d79b76ad-53ce-4480-a2ba-569315572648.png)

Links
https://creativecommons.org/licenses/by/3.0/
https://github.com/mr3saru/landing/blob/main/LICENSE

Use the last version of this endpoint

https://api.github.com/repos/mr3saru/landing/tags

**Comment by vczb** [comment]
> Use the last version of this endpoint
> 
> https://api.github.com/repos/mr3saru/landing/tags

@vameri can you please add a prototype here to help to understand this feature ?

nothing complex, i think a simple PNG or print screen will be great
