### ISSUE TITLE
Add disabled prop to button Ghost and Primary

### ISSUE THREAD

**Issue by vczb** [mr3saru/landing#62]
when the button receive a disabled prop the click needs be blocked, need a visual representation too, like a gray color and not-allowed cursor. you can be creative and propose other things

**Comment by losito105** [comment]
@vczb Could I take a look at this?

**Comment by vczb** [comment]
> @vczb Could I take a look at this?

@losito105  of course, you are welcome.

if you need something i'm available

**Comment by vczb** [comment]
> @vczb Could I take a look at this?

**Just a little tip**

we have or colors here:

styles/theme.css

![image](https://user-images.githubusercontent.com/51221635/156921645-a65e9d49-2efe-47ee-9cda-4e86324c507e.png)

**Comment by losito105** [comment]
Great - that's very helpful, I'll be sure to use those! Thanks!

**Comment by losito105** [comment]
@vczb I submitted a PR to fix this issue here: https://github.com/mr3saru/landing/pull/67. Please let me know if you have any feedback / would like anything changed. Cheers!

**Comment by vczb** [comment]
> @vczb I submitted a PR to fix this issue here: #67. Please let me know if you have any feedback / would like anything changed. Cheers!

Thanks for your PR, i send a feedback to improve it
