### ISSUE TITLE
Add missing anchor tag to Link

### ISSUE THREAD

**Issue by vczb** [mr3saru/landing#64]
![image](https://user-images.githubusercontent.com/51221635/156896701-45c23cd1-5a0c-4414-bc08-c6759f68ba98.png)

in the file`templates/Home/Welcome.tsx` the component <Link> requires a anchor tag as children.

**Comment by losito105** [comment]
Hi @vczb! I submitted a PR to fix this issue here: https://github.com/mr3saru/landing/pull/66. I'd love to continue to help out with the development of this site going forward. Thanks!

**Comment by vczb** [comment]
> @vczb I submitted a PR to fix this issue here: #66. I'd love to continue to help out with the development of this site going forward. Thanks!

hello @losito105 , thanks very much for your contribuiting. we appreciate 

you are very welcome to keep contribuiting on this project 

we approve or PR and merge it with wip branch, when all the issues from v2 milestone are done we will merge it with main. for now we are close this issue
